//Designer:Stephen
//For TI_MSPM0G3507
#ifndef TI_CPAMP_h
#define TI_CPAMP_h
//标准字长头文件引用
#include"stdint.h"
//Power Management Unit Op-Amp Control Register
#define CPAMP_Power_Management_Unit_Op_Amp_Control_Register_Base 0x40400000
#define CPAMP_Power_Management_Unit_Op_Amp_Control_Register_Offset 0x00000510
#define CPAMP_Power_Management_Unit_Op_Amp_Control_Register (*((volatile uint32_t)(CPAMP_Power_Management_Unit_Op-Amp_Control_Register_Base+CPAMP_Power_Management_Unit_Op-Amp_Control_Register_Offset)))
//控制宏
//Module Enable
#define CPAMP_Power_Management_Unit_Op_Amp_Control_Register_Module_Enable 0x00000001
//Non-Inverting Input Enable
#define CPAMP_Power_Management_Unit_Op_Amp_Control_Register_Non_Inverting_Input_Enable 0x00000002
//Inverting Input Channel Select
#define CPAMP_Power_Management_Unit_Op_Amp_Control_Register_Channel_Select_GPAMP_OUT 0x00000000
#define CPAMP_Power_Management_Unit_Op_Amp_Control_Register_Channel_Select_GPAMP_IN_negative 0x00000004
#define CPAMP_Power_Management_Unit_Op_Amp_Control_Register_Channel_Select_GPAMP_Internal 0x00000008
#define CPAMP_Power_Management_Unit_Op_Amp_Control_Register_Channel_Select_Floating 0x0000000C
//Rail-to-Rail Input Mode Select
#define CPAMP_Power_Management_Unit_Op_Amp_Control_Register_Input_Mode_Select_PMOS 0x00000000
#define CPAMP_Power_Management_Unit_Op_Amp_Control_Register_Input_Mode_Select_NMOS 0x00000010
#define CPAMP_Power_Management_Unit_Op_Amp_Control_Register_Input_Mode_Select_PMOS_NMOS_input 0x00000020
#define CPAMP_Power_Management_Unit_Op_Amp_Control_Register_Input_Mode_Select_Sampling_CH0 0x00000030
//Output Enable
#define CPAMP_Power_Management_Unit_Op_Amp_Control_Register_GPAMP_GPAMP_OUT_Connect 0x00000040
//Chopping Clock Mode Select
#define CPAMP_Power_Management_Unit_Op_Amp_Control_Register_Chopping_Clock_Mode_Select_Disable 0x00000000
#define CPAMP_Power_Management_Unit_Op_Amp_Control_Register_Chopping_Clock_Mode_Select_Standard 0x00000400
#define CPAMP_Power_Management_Unit_Op_Amp_Control_Register_Chopping_Clock_Mode_Select_ADC_Aux 0x00000800
//Chopping Clock Frequency Select
#define CPAMP_Power_Management_Unit_Op_Amp_Control_Register_Chopping_Clock_Frequency_Select_16KHz 0x00000000
#define CPAMP_Power_Management_Unit_Op_Amp_Control_Register_Chopping_Clock_Frequency_Select_8KHz 0x00000100
#define CPAMP_Power_Management_Unit_Op_Amp_Control_Register_Chopping_Clock_Frequency_Select_4KHz 0x00000200
#define CPAMP_Power_Management_Unit_Op_Amp_Control_Register_Chopping_Clock_Frequency_Select_2KHz 0x00000300

#endif